# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordbook',
            name='number',
            field=models.CharField(max_length=7, unique=True, verbose_name='Номер книжки'),
        ),
    ]
